# Generated by Django 3.0.3 on 2020-07-30 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200731_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['gdp']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['gdp']},
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_country', to='api.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'name')},
        ),
    ]
