# Generated by Django 3.0.3 on 2020-07-31 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_city_town'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['gdp']},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ['gdp']},
        ),
    ]
