# Generated by Django 3.0.3 on 2020-07-31 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200731_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_city', to='api.City')),
                ('country', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_country', to='api.Country')),
                ('state', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_state', to='api.State')),
                ('town', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_town', to='api.Town')),
            ],
            options={
                'unique_together': {('country', 'state', 'town', 'city')},
            },
        ),
    ]
