# Generated by Django 3.0.3 on 2020-07-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_person'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
    ]
