# Generated by Django 3.0.3 on 2020-07-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200731_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
